{% macro snc_region(country_column='geo.country') %}
CASE
    WHEN {{ country_column }} IN (
        'South Africa',
        'Nigeria',
        'Kenya',
        'Ghana',
        'Uganda',
        'Tanzania',
        'Ethiopia',
        'Côte d’Ivoire',
        'Zambia',
        'Senegal',
        'Rwanda',
        'Mauritania',
        'Zimbabwe',
        'Mauritius',
        'Cameroon',
        'Madagascar',
        'Somalia',
        'Togo',
        'Benin',
        'Mali',
        'Congo - Kinshasa',
        'Angola',
        'Botswana',
        'Burkina Faso',
        'Guinea',
        'Mozambique',
        'Malawi',
        'South Sudan',
        'Sudan',
        'Namibia',
        'Gabon',
        'Lesotho',
        'Seychelles',
        'Congo - Brazzaville',
        'Sierra Leone',
        'Eswatini',
        'Niger',
        'Réunion',
        'Equatorial Guinea',
        'Liberia',
        'Djibouti',
        'Chad',
        'Cape Verde',
        'Gambia',
        'Comoros',
        'Burundi',
        'Mayotte',
        'Eritrea',
        'Guinea-Bissau',
        'Western Sahara'
    ) THEN 'Africa'

    WHEN {{ country_column }} IN (
        'Algeria',
        'Bahrain',
        'Djibouti',
        'Egypt',
        'Iran',
        'Iraq',
        'Jordan',
        'Kuwait',
        'Lebanon',
        'Libya',
        'Morocco',
        'Oman',
        'Qatar',
        'Saudi Arabia',
        'Syria',
        'Tunisia',
        'United Arab Emirates',
        'Yemen'
    ) THEN 'MENA'

    WHEN {{ country_column }} IN (
        'India',
        'Japan',
        'China',
        'South Korea',
        'Bangladesh',
        'Hong Kong',
        'Pakistan',
        'Philippines',
        'Singapore',
        'Taiwan',
        'Georgia',
        'Türkiye',
        'Vietnam',
        'Thailand',
        'Uzbekistan',
        'Malaysia',
        'Armenia',
        'Sri Lanka',
        'Azerbaijan',
        'Kazakhstan',
        'Nepal',
        'Kuwait',
        'Cambodia',
        'Myanmar (Burma)',
        'Mongolia',
        'Kyrgyzstan',
        'Maldives',
        'Macao',
        'Laos',
        'Bhutan',
        'Afghanistan',
        'Brunei',
        'Turkmenistan',
        'Tajikistan',
        'Timor-Leste',
        'Russia',
        'Indonesia',
        'Palestine'
    ) THEN 'Asia'
    
    WHEN {{ country_column }} IN (
        'U.S. Outlying Islands',
        'Australia',
        'New Zealand',
        'Papua New Guinea',
        'Fiji',
        'Guam',
        'New Caledonia',
        'Marshall Islands',
        'Micronesia',
        'Vanuatu',
        'Nauru',
        'Palau',
        'Northern Mariana Islands',
        'American Samoa',
        'French Polynesia',
        'Solomon Islands',
        'Kiribati',
        'Samoa'
    ) THEN 'Australia'

    WHEN {{ country_column }} IN (
        'Canada',
        'United States'
    ) THEN 'Northern America'

    WHEN {{ country_column }} IN (
        'Dominican Republic',
        'Trinidad & Tobago',
        'Bahamas',
        'Puerto Rico',
        'Curaçao',
        'Jamaica',
        'British Virgin Islands',
        'Guadeloupe',
        'Haiti',
        'Martinique',
        'Aruba',
        'Cayman Islands',
        'Barbados',
        'U.S. Virgin Islands',
        'St. Vincent & Grenadines',
        'St. Kitts & Nevis',
        'Sint Maarten',
        'St. Lucia',
        'Antigua & Barbuda',
        'Grenada',
        'Dominica',
        'Turks & Caicos Islands',
        'Cuba',
        'St. Martin',
        'St. Barthélemy',
        'Anguilla'
    ) THEN 'Caribbean'
    
    WHEN {{ country_column }} IN (
        'Mexico',
        'Costa Rica',
        'Guatemala',
        'Panama',
        'Honduras',
        'El Salvador',
        'Nicaragua',
        'Belize'
    ) THEN 'Central America'

    WHEN {{ country_column }} IN (
        'Greenland',
        'Cyprus',
        'Ireland',
        'United Kingdom',
        'Germany',
        'France',
        'Spain',
        'Ukraine',
        'Italy',
        'Poland',
        'Netherlands',
        'Austria',
        'Portugal',
        'Switzerland',
        'Belarus',
        'Greece',
        'Bulgaria',
        'Czechia',
        'Belgium',
        'Hungary',
        'Serbia',
        'Romania',
        'Sweden',
        'Croatia',
        'Denmark',
        'North Macedonia',
        'Lithuania',
        'Slovakia',
        'Finland',
        'Slovenia',
        'Norway',
        'Bosnia & Herzegovina',
        'Albania',
        'Moldova',
        'Luxembourg',
        'Montenegro',
        'Malta',
        'Latvia',
        'Estonia',
        'Iceland',
        'Kosovo',
        'Andorra',
        'Gibraltar',
        'Jersey',
        'Monaco',
        'Isle of Man',
        'Liechtenstein',
        'Guernsey',
        'San Marino',
        'Faroe Islands',
        'Vatican City',
        'Svalbard & Jan Mayen'
    ) THEN 'Europe'
    
    WHEN {{ country_column }} IN ('Israel') THEN 'Israel'
    
    WHEN {{ country_column }} IN (
        'Brazil',
        'Argentina',
        'Colombia',
        'Chile',
        'Peru',
        'Uruguay',
        'Ecuador',
        'Venezuela',
        'Paraguay',
        'Bolivia',
        'Bermuda',
        'Suriname',
        'Guyana',
        'French Guiana'
    ) THEN 'South America'

END AS `snc_region`,
{% endmacro %}